### ISSUE TITLE
 F-Droid

### ISSUE THREAD

**Issue by linsui** [2754LM/oj_helper#4]
请问可以发布到 F-Droid 吗？

**Comment by 2754LM** [comment]
不太了解，之后我试试看

**Comment by linsui** [comment]
好，有问题可以问我 :+1:

**Comment by linsui** [comment]
请问有什么进展吗？如果你没有时间，我可以帮忙打包

**Comment by 2754LM** [comment]
近期还未处理这个。如果你愿意帮忙的话，十分感谢。有什么需要的信息可以联系我。

**Comment by linsui** [comment]
好，那我来打包 :ok_hand:

**Comment by linsui** [comment]
开了个 PR 添加 fastlane

https://github.com/2754LM/oj_helper/tree/main/lib/UI 这个路径应该是小写 ui，在 linux 上大小写影响读取文件。

https://github.com/2754LM/oj_helper/blob/main/pubspec.yaml#L4 这个版本号没有更新？麻烦更新一下，并且在每次更新的时候 version code 要保持递增。

请问 flutter 应该用什么版本？F-Droid 需要知道每个版本对应的 flutter 版本才能自动更新，可以加一个 flutter submodule，或者把 flutter 版本写在一个文件里。

**Comment by 2754LM** [comment]
修改好了，flutter的版本放在了根目录的flutter_version文件中。

**Comment by linsui** [comment]
https://github.com/2754LM/oj_helper/commit/83110250615e51f07d95a2326337e5b3bdc74b77 这里路径和 import 大小写要保持一致，现在两边又反过来了 :rofl:

**Comment by 2754LM** [comment]
改了下，应该没问题了

**Comment by linsui** [comment]
好，没问题了。请问是否要以可重复构建的方式发布？如果你的 apk 是在 windows 上构建的那么应该没办法可重复构建。

**Comment by 2754LM** [comment]
应该不行吧，直接在windows构建的

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/17524 你看看有没有什么问题

**Comment by 2754LM** [comment]
ok的

**Comment by linsui** [comment]
好，过几天就会发布了。之后更新的时候增加版本号，比如 2.2.1+2 然后打 tag 就会自动更新了。谢谢
